### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by GreywaterSoftware** [mohammadg/MyBB-MyAwards#1]
can you please help me with this? every time I try activating the plugin it gives me an error saying "MyBB has experienced an internal SQL error and cannot continue."

**Comment by mobeigi** [comment]
@roast247 This is not the original source for this plugin.

The original source is here:
See: https://community.mybb.com/thread-38904.html

However, that is still a very outdated plugin and won't work with newer version of MyBB so I would recommend using another plugin like this one:
https://community.mybb.com/mods.php?action=view&pid=396

**Comment by GreywaterSoftware** [comment]
> @roast247 This is not the original source for this plugin.
> 
> The original source is here: See: https://community.mybb.com/thread-38904.html
> 
> However, that is still a very outdated plugin and won't work with newer version of MyBB so I would recommend using another plugin like this one: https://community.mybb.com/mods.php?action=view&pid=396

Can I get the original source? That website doesn't allow for signups and you need to be signed up to get it.

**Comment by mobeigi** [comment]
That is the original source.

This repo is based off the original source from this commit: https://github.com/mobeigi/MyBB-MyAwards/commit/df7c722b14be927f50624ee02318b68a3414f2c8

If it no longer works or has issues, you'll have to use something else. Good luck.
